const beerTypes = {
    CLEAR_BEERnFAVS_ON_SIGN_OUT: 'CLEAR_BEERnFAVS_ON_SIGN_OUT',
    TOGGLE_FAVS: 'TOGGLE_FAVS',
    SHOW_BEER_DETAILS: 'SHOW_BEER_DETAILS',
    GET_ALL_BEERS_START: 'GET_ALL_BEERS_START',
    GET_ALL_BEERS_SUCCEED: 'GET_ALL_BEERS_SUCCEED',
    GET_FAVS_START: 'GET_FAVS_START',
    GET_FAVS_SUCCEED: 'GET_FAVS_SUCCEED',
    ADD_FAV_START: 'ADD_FAV_START',
    ADD_FAV_SUCCEED: 'ADD_FAV_SUCCEED',
    DEL_FAV_START: 'DEL_FAV_START',
    DEL_FAV_SUCCEED: 'DEL_FAV_SUCCEED',
}
export default beerTypes